name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression triggers the workflow every day at midnight
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: khairulabsyar
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_projects: yes
          plugin_projects_limit: 4
