name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression triggers the workflow every day at midnight
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: master
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          user: khairulabsyar
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuala_Lumpur
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_projects: yes
          plugin_projects_limit: 4
